#!/usr/bin/env node
// Generates a QML Theme singleton from design/tokens.json.
// Usage: node tools/gen-theme.mjs [--theme dark] [--out ui/qml/Theme.qml]
//
// Colours in tokens.json are CSS-ordered (#RRGGBB / #RRGGBBAA). Qt expects
// #AARRGGBB, so the alpha byte of 8-digit colours is moved to the front here.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const themeName = arg("theme", "dark");
const outPath = resolve(root, arg("out", "ui/qml/Theme.qml"));

const tokens = JSON.parse(readFileSync(resolve(root, "design/tokens.json"), "utf8"));
const theme = tokens.themes?.[themeName];
if (!theme) {
  console.error(`Unknown theme "${themeName}". Available: ${Object.keys(tokens.themes ?? {}).join(", ")}`);
  process.exit(1);
}

const HEX = /^#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;

// "#RRGGBBAA" -> "#AARRGGBB"; "#RRGGBB" unchanged. Lower-cased for stable diffs.
function toQtColor(hex) {
  const h = hex.slice(1).toLowerCase();
  return h.length === 8 ? `#${h.slice(6)}${h.slice(0, 6)}` : `#${h}`;
}

const camel = (parts) =>
  parts
    .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
    .join("");

const lines = [];

function emit(parts, value) {
  const name = camel(parts);
  if (typeof value === "string") {
    if (HEX.test(value)) lines.push(`    readonly property color ${name}: "${toQtColor(value)}"`);
    else lines.push(`    readonly property string ${name}: ${JSON.stringify(value)}`);
  } else if (typeof value === "number") {
    lines.push(`    readonly property real ${name}: ${value}`);
  } else if (Array.isArray(value)) {
    lines.push(`    readonly property var ${name}: ${JSON.stringify(value)}`);
  } else if (value && typeof value === "object") {
    for (const [k, v] of Object.entries(value)) emit([...parts, k], v);
  } else {
    throw new Error(`Unsupported token value at ${parts.join(".")}: ${value}`);
  }
}

// Theme-dependent tokens first, then the theme-independent ones.
for (const [k, v] of Object.entries(theme)) emit([k], v);
for (const [k, v] of Object.entries(tokens)) {
  if (k.startsWith("$") || k === "version" || k === "themes") continue;
  emit([k], v);
}

const out = `// GENERATED by tools/gen-theme.mjs from design/tokens.json (theme: ${themeName}). Do not edit.
pragma Singleton
import QtQuick

QtObject {
    readonly property string themeName: ${JSON.stringify(themeName)}
${lines.join("\n")}
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${lines.length} properties)`);
